### ISSUE TITLE
Caddy V2

### ISSUE THREAD

**Issue by nikooo777** [samdoran/ansible-role-caddy#2]
It looks like Caddy switched to V2 and is deprecating V1.
Downloads from V1 are no longer working.

Any plans on looking into a V2 version of this role?

BR,
Niko

**Comment by samdoran** [comment]
Yup, it's on my todo list. :)

**Comment by samdoran** [comment]
Finally got around to adding this in https://github.com/samdoran/ansible-role-caddy/commit/d6fc39d2784d71f2f77777884d150c731c9811a6. The v2 support is now pretty good. It uses the repositories but will download a custom binary if a list of plugins are provided.
